In [1]:
import torch

## 张量表示由数值组成的数组，0-d: 标量，1-d: 向量，2-d: 矩阵

In [15]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

## 元素的总数

In [6]:
x.numel()

12

In [16]:
x = x.reshape((3, 4))

In [17]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.tensor([[1,2],[1,3]])

tensor([[1, 2],
        [1, 3]])

## 张量之间可以进行加减乘除运算，运算是在元素和元素之间进行的

In [18]:
x = torch.tensor([[1.0,2,3], [1,4,2]])
y = torch.tensor([[2,4,5],[1,4,6]])

In [12]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

tensor([[3., 6., 8.],
        [2., 8., 8.]])
tensor([[-1., -2., -2.],
        [ 0.,  0., -4.]])
tensor([[ 2.,  8., 15.],
        [ 1., 16., 12.]])
tensor([[0.5000, 0.5000, 0.6000],
        [1.0000, 1.0000, 0.3333]])
tensor([[  1.,  16., 243.],
        [  1., 256.,  64.]])


## dim = 0表示在行上面堆叠，dim = 1, 表示在列上面堆叠

In [19]:
torch.cat((x,y), dim=0)
torch.cat((x,y), dim=1)

tensor([[1., 2., 3., 2., 4., 5.],
        [1., 4., 2., 1., 4., 6.]])

## 生成一个逻辑数组

In [20]:
x==y

tensor([[False, False, False],
        [ True,  True, False]])

In [22]:
x.sum()


tensor(13.)

## 注意张量计算时的广播机制

In [24]:
x.reshape(1,6)+y.reshape(6,1)
#结果出来的是一个6*6的矩阵

tensor([[ 3.,  4.,  5.,  3.,  6.,  4.],
        [ 5.,  6.,  7.,  5.,  8.,  6.],
        [ 6.,  7.,  8.,  6.,  9.,  7.],
        [ 2.,  3.,  4.,  2.,  5.,  3.],
        [ 5.,  6.,  7.,  5.,  8.,  6.],
        [ 7.,  8.,  9.,  7., 10.,  8.]])

## 元素的选择

In [25]:
x[1] = 0

In [26]:
x

tensor([[1., 2., 3.],
        [0., 0., 0.]])

In [27]:
id(x)

1956315276992

## 在数据比较大的时候，不要过多复制，这会出现内存方面的问题

In [30]:
type(x.numpy()),type(torch.tensor(x.numpy()))#转为numpy


(numpy.ndarray, torch.Tensor)

## 将数据存在一个CSV文件中

In [31]:
import os

#创建一个文件夹
os.makedirs(os.path.join('..', 'data'), exist_ok=True)

data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [32]:
import pandas as pd

df = pd.read_csv(data_file)
df

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [42]:
inputs, outputs = df.iloc[:, 0:2], df.iloc[:,2]


In [43]:
inputs = inputs.fillna(inputs.mean())

<ipython-input-43-c47d351fd2e9>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [45]:
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [46]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [47]:
X, y = inputs.values, outputs.values

In [48]:
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]]),
 array([127500, 106000, 178100, 140000], dtype=int64))