## 标量 一个数值组成的张量

In [2]:
import torch

x = torch.tensor([2.0])
y = torch.tensor([3.0])

x+y, x-y, x*y, x/y, x**y

(tensor([5.]), tensor([-1.]), tensor([6.]), tensor([0.6667]), tensor([8.]))

## 向量 由多个标量组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
#长度
len(x)

4

## 创建一个矩阵

In [5]:
A = torch.arange(20).reshape(5,4)

A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
# 转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 矩阵的转置等于自己的矩阵被称作对称矩阵

In [8]:
A = torch.tensor([[1, 0, 2],[0, 1, 2], [2, 2, 2]])

In [9]:
A==A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 两个矩阵按照元素相乘被称作哈达玛积（Hadamard product）

In [10]:
B = A.clone()

A*B

tensor([[1, 0, 4],
        [0, 1, 4],
        [4, 4, 4]])

## 求和 按照某个轴求和

In [12]:
#不指定的话就是对所有的元素求和，输出为一个标量

x = torch.arange(20).reshape(5, 4)
x.sum()


tensor(190)

In [17]:
x = torch.arange(2*20).reshape(2, 5, 4)

x.shape, x.sum(),x.sum(axis=0).shape

(torch.Size([2, 5, 4]), tensor(780), torch.Size([5, 4]))

In [20]:
x, x.sum(axis=1)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]))

In [25]:
x = torch.arange(20).reshape(10,2)
x
# 指定哪个维度求和就会把哪个维度丢掉，求和后的张量的维度就是剩下的那几个维度

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

## 求均值

In [28]:
#在求和的基础上除以该维度的数量（numel）
x.sum()/x.numel()

tensor(9.5000)

## 累积求和

In [33]:
x.cumsum(axis=0)

tensor([[  0,   1],
        [  2,   4],
        [  6,   9],
        [ 12,  16],
        [ 20,  25],
        [ 30,  36],
        [ 42,  49],
        [ 56,  64],
        [ 72,  81],
        [ 90, 100]])

## 点积是相同元素乘积的和

In [36]:
x = torch.ones(4, dtype=torch.float32)
y = torch.tensor([1.,2, 3, 4])


In [37]:
#点积
torch.dot(x, y)

tensor(10.)

In [38]:
#还可以表示为按照元素相乘，再求和
torch.sum(x*y)

tensor(10.)

## 矩阵的乘法

In [39]:
A = torch.arange(20).reshape(5, 4)
B = torch.arange(4)

#matrix-vector

A.shape, B.shape, torch.mv(A, B).shape

(torch.Size([5, 4]), torch.Size([4]), torch.Size([5]))

In [40]:
# 上面计算得到的是一个列向量，每个元素是由点积计算得到的

In [57]:
#matrix-matrix
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4,2, dtype=torch.float32)
A.shape, B.shape, torch.mm(A, B).shape



(torch.Size([5, 4]), torch.Size([4, 2]), torch.Size([5, 2]))

## 范数 一个矩阵或者向量的长度
### L1范数 绝对值
### L2范数 平方和开根号

In [58]:
a = torch.tensor([3.0, -4.0])
torch.norm(a)

tensor(5.)

In [59]:
torch.abs(a).sum()

tensor(7.)

### 矩阵的范数 F范数， 矩阵中的每个元素平方求和

In [62]:
torch.norm(torch.ones(4,9))
#将矩阵拉成一个向量，然后平方求和，开根号

tensor(6.)